
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM glassfish:4.0
COPY ./target/hello-world-war-1.0.0 ${GLASSFISH_home}/glassfish/domains/domain1/autodeploy

CMD ["/bin/sh"]
